# Generated by Django 5.1.6 on 2025-02-19 07:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paste', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paste',
            name='id',
        ),
        migrations.AddField(
            model_name='paste',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
