# Generated by Django 5.1.6 on 2025-02-20 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paste', '0003_paste_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paste',
            name='language',
            field=models.CharField(choices=[('Python', 'Python'), ('C++', 'Cpp'), ('C', 'C'), ('Javsacript', 'Js'), ('Java', 'Java'), ('C#', 'Csharp'), ('Other', 'Other')], default='Other', max_length=10),
        ),
    ]
